plantuml_path: "./config/plantuml.jar"  # Путь к файлу plantuml.jar
repository_path: "/путь/к/вашему/git/репозиторию"  # Путь к анализируемому репозиторию
output_path: "./config/output.puml"    # Путь к файлу для генерации диаграммы
tag_name: "v1.0"                       # Имя тега для анализа
