visualization_tool_path: "java -jar ./config/plantuml.jar"  # Путь к plantuml.jar
repository_path: "/path/to/repo"                           # Путь к репозиторию
output_file_path: "/path/to/output/result.puml"            # Путь для сохранения результата
tag_name: "v1.0"                                           # Имя тега для анализа
