plantuml_path: "D:/Users/rashi/PycharmProjects/Configuration-management/homework2/config/plantuml.jar"
repository_path: "D:\Users\rashi\PycharmProjects\Akemu"
output_path: "D:/Users/rashi/PycharmProjects/Configuration-management/homework2/config/output.puml"
tag_name: "v1.0"
